[package]
name = "minver_rs"
version = "0.1.0"
authors = ["Dominic Trottier <domtrottier@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "^0.13"
