name: Rust

on:
  push:
    branches: [ main ]
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always
  MINVER_UPDATE_VERSION: set

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        # Fetch all tags/history
        fetch-depth: 0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Update version
      run: cargo run minver_build_util
    - name: Publish crate
      uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }} 
        args: --allow-dirty
